<a href="https://colab.research.google.com/github/apenkals/Spatial_Programming/blob/main/Sketch04_Penkalski.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
%pip install -q libpysal esda splot mapclassify contextily

In [24]:
DATA_BASE = "https://raw.githubusercontent.com/pjbitterman/KSU_x9076/main/data"

In [31]:
import pandas as pd

In [41]:
precip = pd.read_csv(f"{DATA_BASE}/part1/ohio_precip_2025.csv")
precip.head()

    station_id               name      lat      lon  precip_mm_2025
0  US1OHAB0021  ASHTABULA 1.8 NNE  41.9037 -80.7829           910.4
1  US1OHAD0005       SEAMAN 3.4 E  38.9399 -83.5090          1270.7
2  US1OHAD0006      PEEBLES 4.2 N  39.0075 -83.4146          1174.8
3  US1OHAL0005        LIMA 2.7 NE  40.7739 -84.0800           904.3
4  US1OHAL0008    DELPHOS 2.3 ESE  40.8335 -84.2982           711.4

In [42]:
precip.describe()

              lat         lon  precip_mm_2025
count  410.000000  410.000000      410.000000
mean    40.300644  -83.045526     1008.862439
std      0.804491    1.152487      174.937689
min     38.423900  -84.794400      350.900000
25%     39.670200  -84.094525      895.575000
50%     40.182900  -83.076300     1014.050000
75%     41.037000  -82.125350     1125.500000
max     41.903700  -80.628300     1495.700000

In [43]:
sorted_precip = precip.sort_values("precip_mm_2025")
sorted_precip

,station_id,name,lat,lon,precip_mm_2025
385,USW00004849,ELYRIA LORAIN CO AP,41.3464,-82.1789,350.9
305,USC00332895,FT RECOVERY,40.4100,-84.7856,375.7
145,US1OHJF0011,WINTERSVILLE 0.7 WNW,40.3843,-80.7176,549.6
320,USC00334189,KENTON,40.6486,-83.6061,604.3
390,USW00004857,ASHTABULA CO AP,41.7794,-80.6969,622.3
...,...,...,...,...,...
48,US1OHCN0024,MIDLAND 2.9 S,39.2651,-83.9202,1402.5
108,US1OHGG0007,MIDDLEFIELD 0.6 NE,41.4644,-81.0652,1411.7
16,US1OHAT0021,ATHENS 4.6 ESE,39.3099,-82.0128,1431.6
228,US1OHRC0007,SHELBY 0.6 NNE,40.8900,-82.6558,1488.7
406,USW00093812,CINCINNATI MUNI AP LUNKEN FLD,39.1061,-84.4161,1495.7

In [44]:
wettest_first = precip.sort_values("precip_mm_2025", ascending=False)
wettest_first.head()

,station_id,name,lat,lon,precip_mm_2025
406,USW00093812,CINCINNATI MUNI AP LUNKEN FLD,39.1061,-84.4161,1495.7
228,US1OHRC0007,SHELBY 0.6 NNE,40.8900,-82.6558,1488.7
16,US1OHAT0021,ATHENS 4.6 ESE,39.3099,-82.0128,1431.6
108,US1OHGG0007,MIDDLEFIELD 0.6 NE,41.4644,-81.0652,1411.7
48,US1OHCN0024,MIDLAND 2.9 S,39.2651,-83.9202,1402.5

In [45]:
top_five = wettest_first.head(5)
top_five

,station_id,name,lat,lon,precip_mm_2025
406,USW00093812,CINCINNATI MUNI AP LUNKEN FLD,39.1061,-84.4161,1495.7
228,US1OHRC0007,SHELBY 0.6 NNE,40.8900,-82.6558,1488.7
16,US1OHAT0021,ATHENS 4.6 ESE,39.3099,-82.0128,1431.6
108,US1OHGG0007,MIDDLEFIELD 0.6 NE,41.4644,-81.0652,1411.7
48,US1OHCN0024,MIDLAND 2.9 S,39.2651,-83.9202,1402.5

In [46]:
top_five[["name", "precip_mm_2025"]]

                              name  precip_mm_2025
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7
228                 SHELBY 0.6 NNE          1488.7
16                  ATHENS 4.6 ESE          1431.6
108             MIDDLEFIELD 0.6 NE          1411.7
48                   MIDLAND 2.9 S          1402.5

In [47]:
precip.sort_values("precip_mm_2025", ascending=False).head(5)[["name", "precip_mm_2025"]]

                              name  precip_mm_2025
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7
228                 SHELBY 0.6 NNE          1488.7
16                  ATHENS 4.6 ESE          1431.6
108             MIDDLEFIELD 0.6 NE          1411.7
48                   MIDLAND 2.9 S          1402.5

In [ ]:
# The highest precip is 1495.7 while the mean hovers at 1008.86.
# The difference between the two is approximately 486.84mm.
# The highest being 1495.7 is not very suprising because many
# of the other stations also had large amounts. The local weather
# patterns in these areas must be different causing higher precip.